import os

HOST = ""
AUTH_USER = ""
AUTH_PASS = ""
NAS_PATH = os.path.join("")
AUTH_EMAIL = ""
AUTH_EMAIL_USER = ""
AUTH_EMAIL_PASS = ""
STMP_SERVER = ""
STMP_PORT = 0
TEST_HOST = ""
TEST_USER = ""
TEST_PASS = ""
TEST_EMAIL = ""
TEST_EMAIL_PASS = ""